### ISSUE TITLE
[bug] Constant disconnections

### ISSUE THREAD

**Issue by shaqaruden** [soketi/soketi#630]
I am having an issue where my android client running the pusher SDK constantly disconnects and reconnects to the soketi server. When I was running Laravel Websockets I did not have this problem.

```yaml
websockets:
    image: quay.io/soketi/soketi:latest-16-alpine
    environment:
      SOKETI_DEBUG: 1
      SOKETI_METRICS_SERVER_PORT: 9601
      SOKETI_METRICS_ENABLED: 1
    expose: [9601]
    ports:
      - 9601:9601
    labels:
      caddy: *redacted*
      caddy.@ws.0_header: "Connection *Upgrade*"
      caddy.@ws.1_header: "Upgrade websocket"
      caddy.reverse_proxy: "@ws {{upstreams 6001}}"
    networks:
      - routable
```
