### ISSUE TITLE
Starting Soketi with a JSON config from docker-compose

### ISSUE THREAD

**Issue by hans-lts** [soketi/soketi#688]
## The Question

I feel like I've searched quite extensively and cannot find an answer to this:

Can I start the `quay.io/soketi/soketi:latest-16-alpine` image with a config.json file?

*./soketi/config.json*
```json
{
    "debug": true,
    "port": 6001,
    "appManager.array.apps": [
        {
            "id": "local",
            "key": "local",
            "secret": "local"
        }
    ]
}

```

*./docker-compose.yml*
```yml
soketi:
    image: 'quay.io/soketi/soketi:latest-16-alpine'
    volumes:
        - './soketi/config.json:/opt/config.json'
    command: ["node /app/bin/server.js start --config=/opt/config.json"]
    environment:
        SOKETI_DEBUG: '1'
        SOKETI_METRICS_SERVER_PORT: '9601'
        SOKETI_DEFAULT_APP_ENABLE_CLIENT_MESSAGES: 'true'
    ports:
        - '${SOKETI_PORT:-6001}:6001'
        - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
```

When I run `docker-compose up -d` and look at the debug printout I can see that the application has loaded with the default app-id, app-key, etc values in it's configuration.

I know I could use the array driver and provide the configuration through a .env file however, I'm trying to explore the config.json method.

Am I missing something in the docs?

---

**Is your feature request related to a problem? Please describe.**
Potentially, if there's not already a way to start the docker image with a config file

**Describe the solution you'd like**
Mounting a config.json file in the docker image through docker-compose

**Describe alternatives you've considered**
Looked into array config through the .env. 

Have succeeded when I modified the Dockerfile and rebuilt the image with a different ENTRYPOINT command. If there's a native way to accomplish what I'm trying to do - I'd rather do that.

Thanks in advance! Loving this project
