### ISSUE TITLE
[BUG] Soketi Docker does not work on Digital Ocean App Platform

### ISSUE THREAD

**Issue by JanMisker** [soketi/soketi#724]
I would like to deploy a Soketi instance as part of a Digital Ocean App Platform. I have a simple Dockerfile deployment (just pulling in the Soketi Docker image) and use environment variables to configure the service.
I see the server up and running, and can also see `OK` when accessing it via http.

However... connecting a websocket (wss) does not work, I get a HTTP `200 OK` as response instead of the `101 Switching Protocols`. It seems the http router doesn't pass the right request parameters to Soketi, but I do have another websocket service running and that works fine.

This is probably not a real bug, but a configuration issue, although it would be nice to see documented how to run Soketi as part of a Digital Ocean App. See here for their [App Spec Reference](https://docs.digitalocean.com/products/app-platform/reference/app-spec/)

**Comment by JanMisker** [comment]
Okay I found it. Digital Ocean serves all services an the same domain, and uses paths as routing mechanism. Very convenient, however the default setting is to strip away the path. Soketi needs the full path info (or a way to configure the client to insert an extra path). Anyway, in my case I could fix it by setting `preserve_path_prefix` to `true` for the routes.

A nice example of RTFM (that I even linked to in the post start ;) )
Maybe add this as a note to the docs somewhere?

**Comment by shardick** [comment]
@JanMisker can you share please your dockerfile and DigitalOcean App configuration please?

**Comment by JanMisker** [comment]
In the end I found another way, so I have a normal soketi server without the `preserve_path_prefix`, but on app server level (Laravel) I could set a path prefix.

My dockerfile is a simple one-liner
```
FROM quay.io/soketi/soketi:latest-16-debian AS soketi
```
(`AS soketi` not strictly needed of course).

The relevant parts of my app spec for soketi within app platform
```
- dockerfile_path: soketi/Dockerfile
  envs:
  - key: SOKETI_DEFAULT_APP_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: XXX
  - key: SOKETI_DEFAULT_APP_KEY
    scope: RUN_AND_BUILD_TIME
    value: XXXX 
  - key: SOKETI_DEFAULT_APP_ID
    scope: RUN_AND_BUILD_TIME
    value: XXXXX
  - key: SOKETI_DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "0" 
  github:
    branch: main
    deploy_on_push: true
    repo: XXX
  http_port: 6001
  name: soketi
  routes:
  - path: /soketi
  source_dir: /soketi
```
I set the path prefix environment variable globally because I have Laravel split up in works, jobs, app server so different parts need to talk to soketi to deliver messages:
```
envs:
- key: PUSHER_PATH_PREFIX
  scope: RUN_AND_BUILD_TIME
  value: /soketi/
```
